### ISSUE TITLE
Invalid config for Multiscrape

### ISSUE THREAD

**Issue by johannwilken** [danieldotnl/ha-multiscrape#128]
##Version

v6.3.2

## Configuration

multiscrape:
  - resource: 'https://www.dsewebnet.com/module.php?id=718957445&tab=2'
    scan_interval: 30
    form_submit:
      submit_once: True
      resource: 'https://www.dsewebnet.com/login.php'
      select: #login\[username\]
      input:
        username: 'username'
        password: 'password'
       extra: #login\[password\]
    sensor:
      - select: 'div.widget:nth-child(6) > div:nth-child(1) > svg:nth-child(1) > text:nth-child(8)'
        name: Generator Fuel Level

Logs:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:679
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 4:45:38 PM (1 occurrences)
Last logged: 4:45:38 PM
[140607003037904] The system cannot restart because the configuration is not valid: Invalid config for [multiscrape]: string value is None for dictionary value @ data['multiscrape'][0]['form_submit']['input']['extra']. Got None string value is None for dictionary value @ data['multiscrape'][0]['form_submit']['select']. Got None. (See /config/configuration.yaml, line 137).

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 189, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 679, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Invalid config for [multiscrape]: string value is None for dictionary value @ data['multiscrape'][0]['form_submit']['input']['extra']. Got None
string value is None for dictionary value @ data['multiscrape'][0]['form_submit']['select']. Got None. (See /config/configuration.yaml, line 137).

## Describe the bug

Trying to add to config.yaml and checking config I'm getting error

**Comment by danieldotnl** [comment]
Looks like yaml indentation issues. Please use the forum for support.
