### ISSUE TITLE
device class timestamp error

### ISSUE THREAD

**Issue by metbril** [danieldotnl/ha-multiscrape#174]
## Version of the custom_component

v6.6.0

## Configuration

```yaml
multiscrape:
  - name: NL-Alert
    resource: https://crisis.nl/nl-alert/nl-alerts/
    scan_interval: 60  # seconds
    sensor:
      - unique_id: nl_alert  # entity_id
        name: NL-Alert
        device_class: timestamp. # <-- this produces the error
        select: "#content > div:nth-child(4) > a > h3"
        value_template: |
          {% set upper_value = (value | upper) %}
          {% set stripped_value = upper_value.split('ACTIEF')[-1].strip() if 'ACTIEF' in upper_value else value.strip() %}
          {{ (strptime(stripped_value, "%d-%m-%Y %H:%M:%S", "unavailable") | as_local).isoformat() }}
```

## Describe the bug

I use multiscrape to get a date into a sensor. The webpage returns a string like '31-12-2022 12:34' that I convert to a date time object using a value_template. See below. Everything is working just fine, except setting the `device_class` to timestamp.

## Debug log

**Error log:**

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/sensor/__init__.py:700 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 19:43:15 (1 occurrences) 
Last logged: 19:43:15

[281472885293456] Error handling message: Unknown error (unknown_error) from fe80::14a8:c2dd:93ec:3c02 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2022.10.1 (io.robbie.HomeAssistant; build:2022.424; iPadOS 15.7.1) Mobile/HomeAssistant, like Safari)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 689, in state
    if value.tzinfo is None:
AttributeError: 'str' object has no attribute 'tzinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 646, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/multiscrape/__init__.py", line 190, in _async_trigger_service
    await coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 175, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 82, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 201, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/config/custom_components/multiscrape/entity.py", line 105, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 700, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.nl_alert has timestamp device class but provides state 2023-01-01T00:04:36+01:00:<class 'str'> resulting in ''str' object has no attribute 'tzinfo''
```

I will add a debug log in a separate comment.

**Comment by metbril** [comment]
Debug log:

```txt
2023-01-03 20:01:31.287 DEBUG (MainThread) [custom_components.multiscrape.coordinator] NL-Alert # New run: start (re)loading data from resource
2023-01-03 20:01:31.288 DEBUG (MainThread) [custom_components.multiscrape.coordinator] NL-Alert # Rendered resource template into: https://crisis.nl/nl-alert/nl-alerts/
2023-01-03 20:01:31.288 DEBUG (MainThread) [custom_components.multiscrape.coordinator] NL-Alert # Request data from https://crisis.nl/nl-alert/nl-alerts/
2023-01-03 20:01:31.288 DEBUG (MainThread) [custom_components.multiscrape.http] NL-Alert # Executing page-request with a get to url: https://crisis.nl/nl-alert/nl-alerts/.
2023-01-03 20:01:31.386 DEBUG (MainThread) [custom_components.multiscrape.http] NL-Alert # Response status code received: 200
2023-01-03 20:01:31.387 DEBUG (MainThread) [custom_components.multiscrape.scraper] NL-Alert # Loading the content in BeautifulSoup.
2023-01-03 20:01:31.413 DEBUG (MainThread) [custom_components.multiscrape.coordinator] NL-Alert # Data succesfully refreshed. Sensors will now start scraping to update.
2023-01-03 20:01:31.413 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Finished fetching multiscrape data in 0.126 seconds (success: True)
2023-01-03 20:01:31.413 DEBUG (MainThread) [custom_components.multiscrape.sensor] NL-Alert # NL-Alert # Start scraping to update sensor
2023-01-03 20:01:31.415 DEBUG (MainThread) [custom_components.multiscrape.scraper] NL-Alert # NL-Alert # Tag selected: <h3>1-1-2023 00:04:36</h3>
2023-01-03 20:01:31.415 DEBUG (MainThread) [custom_components.multiscrape.scraper] NL-Alert # NL-Alert # Selector result: 1-1-2023 00:04:36
2023-01-03 20:01:31.416 DEBUG (MainThread) [custom_components.multiscrape.scraper] NL-Alert # NL-Alert # Applying value_template on selector result
2023-01-03 20:01:31.416 DEBUG (MainThread) [custom_components.multiscrape.scraper] NL-Alert # NL-Alert # Final selector value: 2023-01-01T00:04:36+01:00
2023-01-03 20:01:31.416 DEBUG (MainThread) [custom_components.multiscrape.sensor] NL-Alert # NL-Alert # Selected: 2023-01-01T00:04:36+01:00
2023-01-03 20:01:31.416 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 689, in state
    if value.tzinfo is None:
AttributeError: 'str' object has no attribute 'tzinfo'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/config/custom_components/multiscrape/entity.py", line 105, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 700, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.nl_alert has timestamp device class but provides state 2023-01-01T00:04:36+01:00: resulting in ''str' object has no attribute 'tzinfo''
```

**Comment by metbril** [comment]
Perhaps similar:

https://github.com/home-assistant/core/issues/67455

**Comment by metbril** [comment]
I've been doing some testing and it looks like the value_template is computed as a datetime, but then returned to HA as a string, which raises the error. I have tested several variants for value_template, like:

          {{ (strptime(stripped_value, "%d-%m-%Y %H:%M:%S", "unavailable") | as_local).isoformat() }}

          {{ (strptime(stripped_value, "%d-%m-%Y %H:%M:%S", "unavailable") | as_local) }}

          {{ (strptime(stripped_value, "%d-%m-%Y %H:%M:%S", "unavailable") | as_local).tzinfo }}

The latter produces "Europe/Amsterdam". A string, purposely, to show that at this stage the template is a real datetime object.

**Comment by danieldotnl** [comment]
It is related to this one: https://github.com/home-assistant/core/issues/83949, will fix it.

**Comment by danieldotnl** [comment]
Btw for personal interest: could you share your full NL alert config? Tnx!

**Comment by metbril** [comment]
My config is in my online repo: 

https://github.com/metbril/home-assistant-config/blob/faa3f30bc61757354c8ea12a74f96d68842191aa/packages/beta/nl_alert.yaml

**Comment by danieldotnl** [comment]
Please check [v6.6.1](https://github.com/danieldotnl/ha-multiscrape/releases/tag/v6.6.1)!

**Comment by metbril** [comment]
Awesome. It appears to be working!

<img width="1016" alt="Schermafbeelding 2023-01-08 om 11 21 11" src="https://user-images.githubusercontent.com/559346/211190873-ab376cef-37fc-41e2-9fe4-1bc56443eb4b.png">
