### ISSUE TITLE
make scan_interval optionnal

### ISSUE THREAD

**Issue by roumano** [danieldotnl/ha-multiscrape#188]
It's possible to make the scan_interval optional ?
As i want to run it rarely ( 3 times per day at a precise time) the scan_interval is not a option.

So i use ( and it's working great) them via a automation `service: multiscrape.trigger_XXXX` ( and also manually via a button refresh )

actually i set the scan_interval to a very long integer but ideally if it's can be avoid ...

* the solution i'd like
`scan_interval: 0`

**Comment by roumano** [comment]
Do you think it's already possible, like put `0` or `-1` in scan_interval attribut or remove the `scan_interval` attribut ( if yes need to add documentation about it) 
Or possible to add this feature

**Comment by danieldotnl** [comment]
Took a while but I'll start working on this one! Do you happen to know other integrations that support this, so I can implement the same logic? I believe the rest integration doesn't support scan_interval 0 or -1.

**Comment by roumano** [comment]
I don't see ( or even serach) for a similar option on other integration

In the rest integration, it's adding the refresh by this small function : refresh_coroutines.append
```
        scan_interval: timedelta = conf.get(CONF_SCAN_INTERVAL, DEFAULT_SCAN_INTERVAL)
        resource_template: template.Template | None = conf.get(CONF_RESOURCE_TEMPLATE)
        rest = create_rest_data_from_config(hass, conf)
        coordinator = _rest_coordinator(hass, rest, resource_template, scan_interval)
        refresh_coroutines.append(coordinator.async_refresh())
````

**Comment by roumano** [comment]
installed just now, now need to wait one or more day to see if it's working as expected.
Big thanks !!!

**Comment by danieldotnl** [comment]
Any findings?

**Comment by roumano** [comment]
Yes, when i restart home assistant it's crashing (but only when i restart home assistant, a curl of this url is working juste after ) : 


```
mai 08 22:13:47 pi hass[2752805]: 2023-05-08 22:13:47.708 DEBUG (MainThread) [custom_components.multiscrape.http] edf_tempo # Timeout error while executing get request to url: https://particulier.edf.fr/services/rest/referentiel/searchTempoStore?dateRelevant=2023-05-08.
mai 08 22:13:47 pi hass[2752805]:  Error message:
mai 08 22:13:47 pi hass[2752805]:  ConnectTimeout('')
mai 08 22:13:47 pi hass[2752805]: 2023-05-08 22:13:47.708 ERROR (MainThread) [custom_components.multiscrape.coordinator] edf_tempo # Updating failed with exception:
mai 08 22:13:47 pi hass[2752805]: 2023-05-08 22:13:47.721 ERROR (MainThread) [custom_components.multiscrape.coordinator] Unexpected error fetching multiscrape data: 'MultiscrapeDataUpdateCoordinator' object has no attribute '_async_unsub_refresh'
mai 08 22:13:47 pi hass[2752805]: Traceback (most recent call last):
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
mai 08 22:13:47 pi hass[2752805]:     yield
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 110, in connect_tcp
mai 08 22:13:47 pi hass[2752805]:     with anyio.fail_after(timeout):
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
mai 08 22:13:47 pi hass[2752805]:     raise TimeoutError
mai 08 22:13:47 pi hass[2752805]: TimeoutError
mai 08 22:13:47 pi hass[2752805]: During handling of the above exception, another exception occurred:
mai 08 22:13:47 pi hass[2752805]: Traceback (most recent call last):
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
mai 08 22:13:47 pi hass[2752805]:     yield
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
mai 08 22:13:47 pi hass[2752805]:     resp = await self._pool.handle_async_request(req)
mai 08 22:13:47 pi hass[2752805]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
mai 08 22:13:47 pi hass[2752805]:     raise exc
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
mai 08 22:13:47 pi hass[2752805]:     response = await connection.handle_async_request(request)
mai 08 22:13:47 pi hass[2752805]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
mai 08 22:13:47 pi hass[2752805]:     raise exc
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
mai 08 22:13:47 pi hass[2752805]:     stream = await self._connect(request)
mai 08 22:13:47 pi hass[2752805]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection.py", line 111, in _connect
mai 08 22:13:47 pi hass[2752805]:     stream = await self._network_backend.connect_tcp(**kwargs)
mai 08 22:13:47 pi hass[2752805]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/backends/auto.py", line 29, in connect_tcp
mai 08 22:13:47 pi hass[2752805]:     return await self._backend.connect_tcp(
mai 08 22:13:47 pi hass[2752805]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 109, in connect_tcp
mai 08 22:13:47 pi hass[2752805]:     with map_exceptions(exc_map):
mai 08 22:13:47 pi hass[2752805]:   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
mai 08 22:13:47 pi hass[2752805]:     self.gen.throw(typ, value, traceback)
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
mai 08 22:13:47 pi hass[2752805]:     raise to_exc(exc)
mai 08 22:13:47 pi hass[2752805]: httpcore.ConnectTimeout
mai 08 22:13:47 pi hass[2752805]: The above exception was the direct cause of the following exception:
mai 08 22:13:47 pi hass[2752805]: Traceback (most recent call last):
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/.homeassistant/custom_components/multiscrape/coordinator.py", line 85, in _async_update_data
mai 08 22:13:47 pi hass[2752805]:     response = await self._http.async_request(
mai 08 22:13:47 pi hass[2752805]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/.homeassistant/custom_components/multiscrape/http.py", line 54, in async_request
mai 08 22:13:47 pi hass[2752805]:     response = await self._client.request(
mai 08 22:13:47 pi hass[2752805]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1533, in request
mai 08 22:13:47 pi hass[2752805]:     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
mai 08 22:13:47 pi hass[2752805]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1620, in send
mai 08 22:13:47 pi hass[2752805]:     response = await self._send_handling_auth(
mai 08 22:13:47 pi hass[2752805]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
mai 08 22:13:47 pi hass[2752805]:     response = await self._send_handling_redirects(
mai 08 22:13:47 pi hass[2752805]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
mai 08 22:13:47 pi hass[2752805]:     response = await self._send_single_request(request)
mai 08 22:13:47 pi hass[2752805]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1722, in _send_single_request
mai 08 22:13:47 pi hass[2752805]:     response = await transport.handle_async_request(request)
mai 08 22:13:47 pi hass[2752805]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
mai 08 22:13:47 pi hass[2752805]:     with map_httpcore_exceptions():
mai 08 22:13:47 pi hass[2752805]:   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
mai 08 22:13:47 pi hass[2752805]:     self.gen.throw(typ, value, traceback)
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
mai 08 22:13:47 pi hass[2752805]:     raise mapped_exc(message) from exc
mai 08 22:13:47 pi hass[2752805]: httpx.ConnectTimeout
mai 08 22:13:47 pi hass[2752805]: During handling of the above exception, another exception occurred:
mai 08 22:13:47 pi hass[2752805]: Traceback (most recent call last):
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
mai 08 22:13:47 pi hass[2752805]:     self.data = await self._async_update_data()
mai 08 22:13:47 pi hass[2752805]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/.homeassistant/custom_components/multiscrape/coordinator.py", line 103, in _async_update_data
mai 08 22:13:47 pi hass[2752805]:     self._async_unsub_refresh()
mai 08 22:13:47 pi hass[2752805]:     ^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]: AttributeError: 'MultiscrapeDataUpdateCoordinator' object has no attribute '_async_unsub_refresh'
mai 08 22:13:47 pi hass[2752805]: 2023-05-08 22:13:47.933 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Finished fetching multiscrape data in 13.032 seconds (success: False)
mai 08 22:13:47 pi hass[2752805]: 2023-05-08 22:13:47.981 DEBUG (MainThread) [custom_components.multiscrape.http] rte_tempo_planning # Timeout error while executing get request to url: https://particulier.edf.fr/services/rest/referentiel/getNbTempoDays?TypeAlerte=TEMPO.
mai 08 22:13:47 pi hass[2752805]:  Error message:
mai 08 22:13:47 pi hass[2752805]:  ConnectTimeout('')
mai 08 22:13:47 pi hass[2752805]: 2023-05-08 22:13:47.981 ERROR (MainThread) [custom_components.multiscrape.coordinator] rte_tempo_planning # Updating failed with exception:
mai 08 22:13:48 pi hass[2752805]: 2023-05-08 22:13:47.985 ERROR (MainThread) [custom_components.multiscrape.coordinator] Unexpected error fetching multiscrape data: 'MultiscrapeDataUpdateCoordinator' object has no attribute '_async_unsub_refresh'
mai 08 22:13:48 pi hass[2752805]: Traceback (most recent call last):
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 111, in connect_tcp
mai 08 22:13:48 pi hass[2752805]:     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
mai 08 22:13:48 pi hass[2752805]:                                    ^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 213, in connect_tcp
mai 08 22:13:48 pi hass[2752805]:     async with create_task_group() as tg:
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
mai 08 22:13:48 pi hass[2752805]:     raise exceptions[0]
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 733, in task_done
mai 08 22:13:48 pi hass[2752805]:     exc = _task.exception()
mai 08 22:13:48 pi hass[2752805]:           ^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
mai 08 22:13:48 pi hass[2752805]:     stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
mai 08 22:13:48 pi hass[2752805]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
mai 08 22:13:48 pi hass[2752805]:     await get_running_loop().create_connection(
mai 08 22:13:48 pi hass[2752805]:   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
mai 08 22:13:48 pi hass[2752805]:     transport, protocol = await self._create_connection_transport(
mai 08 22:13:48 pi hass[2752805]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
mai 08 22:13:47 pi hass[2752805]:     with map_httpcore_exceptions():
mai 08 22:13:47 pi hass[2752805]:   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
mai 08 22:13:47 pi hass[2752805]:     self.gen.throw(typ, value, traceback)
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
mai 08 22:13:47 pi hass[2752805]:     raise mapped_exc(message) from exc
mai 08 22:13:47 pi hass[2752805]: httpx.ConnectTimeout
mai 08 22:13:47 pi hass[2752805]: During handling of the above exception, another exception occurred:
mai 08 22:13:47 pi hass[2752805]: Traceback (most recent call last):
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
mai 08 22:13:47 pi hass[2752805]:     self.data = await self._async_update_data()
mai 08 22:13:47 pi hass[2752805]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]:   File "/data/homeassistant/.homeassistant/custom_components/multiscrape/coordinator.py", line 103, in _async_update_data
mai 08 22:13:47 pi hass[2752805]:     self._async_unsub_refresh()
mai 08 22:13:47 pi hass[2752805]:     ^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:47 pi hass[2752805]: AttributeError: 'MultiscrapeDataUpdateCoordinator' object has no attribute '_async_unsub_refresh'
mai 08 22:13:47 pi hass[2752805]: 2023-05-08 22:13:47.933 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Finished fetching multiscrape data in 13.032 seconds (success: False)
mai 08 22:13:47 pi hass[2752805]: 2023-05-08 22:13:47.981 DEBUG (MainThread) [custom_components.multiscrape.http] rte_tempo_planning # Timeout error while executing get request to url: https://particulier.edf.fr/services/rest/referentiel/getNbTempoDays?TypeAlerte=TEMPO.
mai 08 22:13:47 pi hass[2752805]:  Error message:
mai 08 22:13:47 pi hass[2752805]:  ConnectTimeout('')
mai 08 22:13:47 pi hass[2752805]: 2023-05-08 22:13:47.981 ERROR (MainThread) [custom_components.multiscrape.coordinator] rte_tempo_planning # Updating failed with exception:
mai 08 22:13:48 pi hass[2752805]: 2023-05-08 22:13:47.985 ERROR (MainThread) [custom_components.multiscrape.coordinator] Unexpected error fetching multiscrape data: 'MultiscrapeDataUpdateCoordinator' object has no attribute '_async_unsub_refresh'
mai 08 22:13:48 pi hass[2752805]: Traceback (most recent call last):
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 111, in connect_tcp
mai 08 22:13:48 pi hass[2752805]:     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
mai 08 22:13:48 pi hass[2752805]:                                    ^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 213, in connect_tcp
mai 08 22:13:48 pi hass[2752805]:     async with create_task_group() as tg:
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
mai 08 22:13:48 pi hass[2752805]:     raise exceptions[0]
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 733, in task_done
mai 08 22:13:48 pi hass[2752805]:     exc = _task.exception()
mai 08 22:13:48 pi hass[2752805]:           ^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
mai 08 22:13:48 pi hass[2752805]:     stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
mai 08 22:13:48 pi hass[2752805]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
mai 08 22:13:48 pi hass[2752805]:     await get_running_loop().create_connection(
mai 08 22:13:48 pi hass[2752805]:   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
mai 08 22:13:48 pi hass[2752805]:     transport, protocol = await self._create_connection_transport(
mai 08 22:13:48 pi hass[2752805]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
mai 08 22:13:48 pi hass[2752805]:     await waiter
mai 08 22:13:48 pi hass[2752805]: asyncio.exceptions.CancelledError
mai 08 22:13:48 pi hass[2752805]: During handling of the above exception, another exception occurred:
mai 08 22:13:48 pi hass[2752805]: Traceback (most recent call last):
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
mai 08 22:13:48 pi hass[2752805]:     yield
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 110, in connect_tcp
mai 08 22:13:48 pi hass[2752805]:     with anyio.fail_after(timeout):
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
mai 08 22:13:48 pi hass[2752805]:     raise TimeoutError
mai 08 22:13:48 pi hass[2752805]: TimeoutError
mai 08 22:13:48 pi hass[2752805]: During handling of the above exception, another exception occurred:
mai 08 22:13:48 pi hass[2752805]: Traceback (most recent call last):
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
mai 08 22:13:48 pi hass[2752805]:     yield
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
mai 08 22:13:48 pi hass[2752805]:     resp = await self._pool.handle_async_request(req)
mai 08 22:13:48 pi hass[2752805]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
mai 08 22:13:48 pi hass[2752805]:     raise exc
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
mai 08 22:13:48 pi hass[2752805]:     response = await connection.handle_async_request(request)
mai 08 22:13:48 pi hass[2752805]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
mai 08 22:13:48 pi hass[2752805]:     raise exc
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
mai 08 22:13:48 pi hass[2752805]:     stream = await self._connect(request)
mai 08 22:13:48 pi hass[2752805]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection.py", line 111, in _connect
mai 08 22:13:48 pi hass[2752805]:     stream = await self._network_backend.connect_tcp(**kwargs)
mai 08 22:13:48 pi hass[2752805]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/backends/auto.py", line 29, in connect_tcp
mai 08 22:13:48 pi hass[2752805]:     return await self._backend.connect_tcp(
mai 08 22:13:48 pi hass[2752805]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 109, in connect_tcp
mai 08 22:13:48 pi hass[2752805]:     with map_exceptions(exc_map):
mai 08 22:13:48 pi hass[2752805]:   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
mai 08 22:13:48 pi hass[2752805]:     self.gen.throw(typ, value, traceback)
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
mai 08 22:13:48 pi hass[2752805]:     raise to_exc(exc)
mai 08 22:13:48 pi hass[2752805]: httpcore.ConnectTimeout
mai 08 22:13:48 pi hass[2752805]: The above exception was the direct cause of the following exception:
mai 08 22:13:48 pi hass[2752805]: Traceback (most recent call last):
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/.homeassistant/custom_components/multiscrape/coordinator.py", line 85, in _async_update_data
mai 08 22:13:48 pi hass[2752805]:     response = await self._http.async_request(
mai 08 22:13:48 pi hass[2752805]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/.homeassistant/custom_components/multiscrape/http.py", line 54, in async_request
mai 08 22:13:48 pi hass[2752805]:     response = await self._client.request(
mai 08 22:13:48 pi hass[2752805]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1533, in request
mai 08 22:13:48 pi hass[2752805]:     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
mai 08 22:13:48 pi hass[2752805]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1620, in send
mai 08 22:13:48 pi hass[2752805]:     response = await self._send_handling_auth(
mai 08 22:13:48 pi hass[2752805]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
mai 08 22:13:48 pi hass[2752805]:     response = await self._send_handling_redirects(
mai 08 22:13:48 pi hass[2752805]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
mai 08 22:13:48 pi hass[2752805]:     response = await self._send_single_request(request)
mai 08 22:13:48 pi hass[2752805]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/pythmultion3.11/site-packages/httpx/_client.py", line 1722, in _send_single_request
mai 08 22:13:48 pi hass[2752805]:     response = await transport.handle_async_request(request)
mai 08 22:13:48 pi hass[2752805]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
mai 08 22:13:48 pi hass[2752805]:     with map_httpcore_exceptions():
mai 08 22:13:48 pi hass[2752805]:   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
mai 08 22:13:48 pi hass[2752805]:     self.gen.throw(typ, value, traceback)
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
mai 08 22:13:48 pi hass[2752805]:     raise mapped_exc(message) from exc
mai 08 22:13:48 pi hass[2752805]: httpx.ConnectTimeout
mai 08 22:13:48 pi hass[2752805]: During handling of the above exception, another exception occurred:
mai 08 22:13:48 pi hass[2752805]: Traceback (most recent call last):
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
mai 08 22:13:48 pi hass[2752805]:     self.data = await self._async_update_data()
mai 08 22:13:48 pi hass[2752805]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]:   File "/data/homeassistant/.homeassistant/custom_components/multiscrape/coordinator.py", line 103, in _async_update_data
mai 08 22:13:48 pi hass[2752805]:     self._async_unsub_refresh()
mai 08 22:13:48 pi hass[2752805]:     ^^^^^^^^^^^^^^^^^^^^^^^^^
mai 08 22:13:48 pi hass[2752805]: AttributeError: 'MultiscrapeDataUpdateCoordinator' object has no attribute '_async_unsub_refresh'
mai 08 22:13:48 pi hass[2752805]: 2023-05-08 22:13:48.045 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Finished fetching multiscrape data in 12.985 seconds (success: False)
mai 08 22:13:48 pi hass[2752805]: 2023-05-08 22:13:48.247 DEBUG (MainThread) [custom_components.multiscrape.http] Qualité de l'air Vaulnaveys # Timeout error while executing get request to url: http://api.atmo-aura.fr/api/v1/communes/38529/indices/atmo?api_token=39ca766761b93cd79a0bceeede7b3bef&date_calcul=yesterday&echeance=1.
mai 08 22:13:48 pi hass[2752805]:  Error message:
mai 08 22:13:48 pi hass[2752805]:  ConnectTimeout('')
```

**Comment by danieldotnl** [comment]
Which version of HA are you running?

**Comment by roumano** [comment]
2023.04.05

If you want, I can upgrade to 2023.05, ...

**Comment by danieldotnl** [comment]
Yes, I think upgrading will solve this error. Not the timeout (that's probably caused by the external server) but the exception while handling the timeout.
Apparently, I used a function that was only added in 2023.5.

**Comment by roumano** [comment]
Yes, no more error in the log since my upgrade, so everything look great, thank you !!!
