### ISSUE TITLE
multiscrape issue with HA 2023.07

### ISSUE THREAD

**Issue by roumano** [danieldotnl/ha-multiscrape#218]
## Configuration

Multiscrape is set to grap data from this url : https://particulier.edf.fr/services/rest/referentiel/searchTempoStore?dateRelevant=2023-07-07  , with this code (long but basic value_template ): 
```yaml
- name: edf_tempo
  resource: https://particulier.edf.fr/services/rest/referentiel/searchTempoStore?dateRelevant={{now().strftime("%Y-%m-%d")}}
  scan_interval: 100
  headers:
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Content-Type: application/json
    User-Agent: Wget/1.20.3 (linux-gnu)
  button:
    - unique_id: rte_refresh
      name: EDF Force refresh Tempo Information
  sensor:
    - unique_id: edf_tempo_current
      name: EDF Tempo Couleur Aujourd'huit
      icon: mdi:flash
      value_template: >
        {% if value_json.couleurJourJ in ['TEMPO_BLEU','TEMPO_BLANC','TEMPO_ROUGE'] %}
          {{ value_json.couleurJourJ |regex_replace(find='^TEMPO_', replace='') }}
        {% else %}
          unknown
        {% endif %}
    - unique_id: edf_tempo_tomorrow
      name: EDF Tempo Couleur Demain
      icon: mdi:flash-outline
      value_template: >
        {% if value_json.couleurJourJ1 in ['TEMPO_BLEU','TEMPO_BLANC','TEMPO_ROUGE'] %}
          {{ value_json.couleurJourJ1 |regex_replace(find='^TEMPO_', replace='') }}
        {% else %}
          unknown
        {% endif %}
    - unique_id: edf_tempo_tomorrow_cost
      name: EDF Tempo Tarif Demain
      icon: mdi:currency-eur
      device_class: monetary
      unit_of_measurement: "€/kWh"
      value_template: >
        {% if (value_json.couleurJourJ1 == 'TEMPO_BLEU') %}
          0.1249
        {% elif (value_json.couleurJourJ1 == 'TEMPO_BLANC') %}
          0.1508
        {% elif (value_json.couleurJourJ1 == 'TEMPO_ROUGE') %}
          0.6712
        {% else %}
          0
        {% endif %}
    - unique_id: edf_tempo_current_cost
      name: EDF Tempo Tarif Aujourd'huit
      icon: mdi:currency-eur
      device_class: monetary
      unit_of_measurement: "€/kWh"
      value_template: >
        {% if (value_json.couleurJourJ == 'TEMPO_BLEU') %}
          {% if ((now()| as_local).hour >= 22 or (now()|as_local).hour < 6) %}
            0.097
          {% else %}
            0.1249
          {% endif %}
        {% elif (value_json.couleurJourJ == 'TEMPO_BLANC') %}
          {% if ((now()| as_local).hour >= 22 or (now()|as_local).hour < 6) %}
            0.1140
          {% else %}
            0.1508
          {% endif %}
        {% elif (value_json.couleurJourJ == 'TEMPO_ROUGE') %}
          {% if ((now()| as_local).hour >= 22 or (now()|as_local).hour < 6) %}
            0.1216
          {% else %}
            0.6712
          {% endif %}
        {% else %}
          0
        {% endif %}
    - unique_id: edf_tempo_hier
      name: EDF Tempo Hier
      icon: mdi:currency-eur
      value_template: >
        {{ states('sensor.edf_tempo_current') }}
```

- If i remove the edf_tempo multiscrape sensor , it's failing ith the same error on the next multiscrape sensor.

## Describe the bug
After a upgrade HomeAssistant to 2023.07.01, the multiscrape raide a Traceback

## Debug log

```text
juil. 07 19:08:11 pi hass[1709425]: 2023-07-07 19:08:11.579 DEBUG (MainThread) [custom_components.multiscrape] edf_tempo # Initializing scraper
juil. 07 19:08:11 pi hass[1709425]: 2023-07-07 19:08:11.580 DEBUG (MainThread) [custom_components.multiscrape.scraper] edf_tempo # Initializing scraper
juil. 07 19:08:11 pi hass[1709425]: 2023-07-07 19:08:11.580 DEBUG (MainThread) [custom_components.multiscrape.http] edf_tempo # Initializing http wrapper
juil. 07 19:08:11 pi hass[1709425]: 2023-07-07 19:08:11.580 DEBUG (MainThread) [custom_components.multiscrape] edf_tempo # Initializing coordinator
juil. 07 19:08:11 pi hass[1709425]: 2023-07-07 19:08:11.580 DEBUG (MainThread) [custom_components.multiscrape.coordinator] edf_tempo # Scan interval is 0:01:00
juil. 07 19:08:11 pi hass[1709425]: 2023-07-07 19:08:11.582 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [545681469072] 'edf_tempo'
juil. 07 19:08:11 pi hass[1709425]: Traceback (most recent call last):
juil. 07 19:08:11 pi hass[1709425]:   File "/data/homeassistant/lib/python3.11/site-packages/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
juil. 07 19:08:11 pi hass[1709425]:     await hass.services.async_call(
juil. 07 19:08:11 pi hass[1709425]:   File "/data/homeassistant/lib/python3.11/site-packages/homeassistant/core.py", line 1957, in async_call
juil. 07 19:08:11 pi hass[1709425]:     response_data = await coro
juil. 07 19:08:11 pi hass[1709425]:                     ^^^^^^^^^^
juil. 07 19:08:11 pi hass[1709425]:   File "/data/homeassistant/lib/python3.11/site-packages/homeassistant/core.py", line 1997, in _execute_service
juil. 07 19:08:11 pi hass[1709425]:     return await cast(
juil. 07 19:08:11 pi hass[1709425]:            ^^^^^^^^^^^
juil. 07 19:08:11 pi hass[1709425]:   File "/data/homeassistant/.homeassistant/custom_components/multiscrape/__init__.py", line 82, in reload_service_handler
juil. 07 19:08:11 pi hass[1709425]:     await _async_process_config(hass, conf)
juil. 07 19:08:11 pi hass[1709425]:   File "/data/homeassistant/.homeassistant/custom_components/multiscrape/__init__.py", line 162, in _async_process_config
juil. 07 19:08:11 pi hass[1709425]:     await _register_services(hass, target_name, coordinator)
juil. 07 19:08:11 pi hass[1709425]:   File "/data/homeassistant/.homeassistant/custom_components/multiscrape/__init__.py", line 208, in _register_services
juil. 07 19:08:11 pi hass[1709425]:     async_set_service_schema(hass, DOMAIN, target_name, service_desc)
juil. 07 19:08:11 pi hass[1709425]:   File "/data/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 687, in async_set_service_schema
juil. 07 19:08:11 pi hass[1709425]:     response := hass.services.supports_response(domain, service)
juil. 07 19:08:11 pi hass[1709425]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
juil. 07 19:08:11 pi hass[1709425]:   File "/data/homeassistant/lib/python3.11/site-packages/homeassistant/core.py", line 1763, in supports_response
juil. 07 19:08:11 pi hass[1709425]:     if not (handler := self._services[domain][service]):
juil. 07 19:08:11 pi hass[1709425]:                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
juil. 07 19:08:11 pi hass[1709425]: KeyError: 'edf_tempo'
juil. 07 19:08:11 pi hass[1709425]: 2023-07-07 19:08:11.598 WARNING (MainThread) [py.warnings] /data/homeassistant/lib/python3.11/site-packages/homeassistant/components/websocket_api/commands.py:226: RuntimeWarning: coroutine 'DataUpdateCoordinator.async_refresh' was never awaited
juil. 07 19:08:11 pi hass[1709425]:   connection.send_error(msg["id"], const.ERR_UNKNOWN_ERROR, str(err))
```

**Comment by roumano** [comment]
oups, i saw, just after the new version (v6.7.1) which fixing the issue
