### ISSUE TITLE
Component failing to load after HA update

### ISSUE THREAD

**Issue by madpsy** [danieldotnl/ha-multiscrape#219]
## Version of the custom_component

Latest from master branch as of today. HA version  2023.7.1

## Configuration

```
multiscrape:
  resource: https://www.hamqsl.com/solarxml.php
  scan_interval: 3600
  sensor:
    - unique_id: solar_flux_index
      name: "Solar Flux Index"
      select: "solarflux"
      value_template: '{{ value.strip()|int }}'
      state_class: measurement
      icon: mdi:weather-sunny-alert
```

## Describe the bug

Component fails to load. This was after an update to latest HA 2023.7.1. I then also updated the component itself from master but to no avail.

## Debug log

```
2023-07-08 07:01:18.931 ERROR (MainThread) [homeassistant.setup] Error during setup of component multiscrape
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/multiscrape/__init__.py", line 82, in async_setup
    return await _async_process_config(hass, entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multiscrape/__init__.py", line 155, in _async_process_config
    await _register_services(hass, target_name, coordinator)
  File "/config/custom_components/multiscrape/__init__.py", line 201, in _register_services
    async_set_service_schema(hass, DOMAIN, target_name, service_desc)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 687, in async_set_service_schema
    response := hass.services.supports_response(domain, service)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1763, in supports_response
    if not (handler := self._services[domain][service]):
                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'scraper_noname_0'
2023-07-08 07:01:18.950 WARNING (MainThread) [py.warnings] /usr/src/homeassistant/homeassistant/setup.py:303: RuntimeWar
ning: coroutine 'DataUpdateCoordinator.async_refresh' was never awaited
  return False

```

**Comment by terdmanski** [comment]
Same here :(

Logger: homeassistant.setup
Source: core.py:1763 
First occurred: 7 lipca 2023 o 22:43:41 (1 occurrences) 
Last logged: 7 lipca 2023 o 22:43:41

Error during setup of component multiscrape
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/multiscrape/__init__.py", line 89, in async_setup
    return await _async_process_config(hass, entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multiscrape/__init__.py", line 162, in _async_process_config
    await _register_services(hass, target_name, coordinator)
  File "/config/custom_components/multiscrape/__init__.py", line 208, in _register_services
    async_set_service_schema(hass, DOMAIN, target_name, service_desc)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 687, in async_set_service_schema
    response := hass.services.supports_response(domain, service)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1763, in supports_response
    if not (handler := self._services[domain][service]):
                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'scraper_noname_0'

**Comment by ClausSamuelsen** [comment]
Thanks. Version 6.7.1 solved the problem.

**Comment by madpsy** [comment]
Thanks - confirmed now working.
