### ISSUE TITLE
Error with 2023.7.1 and/or Esphome 

### ISSUE THREAD

**Issue by fuglphoenix** [danieldotnl/ha-multiscrape#222]
after updating to 2023.7.1 my esphome device fails to initialise. 
It is a esp32 with a CO2-sensor. it measures CO2 and registers a HA-service to calibrate the sensor.
it might be related to #215 
esphome version: 2023.6.5

## Debug log

```
Logger: homeassistant.config_entries
Source: core.py:1763
First occurred: 19:35:39 (2 occurrences)
Last logged: 19:35:39

Error setting up entry co2-2 for esphome
Error setting up entry co2-1 for esphome
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 479, in async_setup_entry
    await _setup_services(hass, entry_data, services)
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 669, in _setup_services
    await _register_service(hass, entry_data, service)
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 636, in _register_service
    async_set_service_schema(hass, DOMAIN, service_name, service_desc)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 687, in async_set_service_schema
    response := hass.services.supports_response(domain, service)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1763, in supports_response
    if not (handler := self._services[domain][service]):
                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'co2_2_Callibrate'
```

**Comment by fuglphoenix** [comment]
sorry wrong place to write this :-D
