### ISSUE TITLE
How to read attribute from tag?

### ISSUE THREAD

**Issue by DimkaInc** [danieldotnl/ha-multiscrape#28]
In the previous version, I could read the value of the tag attributes. As shown below. 

```
- platform: multiscrape
  name: ralay device
  username: !secret pwr_sw_username
  password: !secret pwr_sw_password
  resource: !secret pwr_sw_address
  scan_interval: 5
  selectors:
    rele_1:
      name: relay_1
      select: "button[name=relayon1] ~ img"
      attribute: "src"
      value_template: '{{ value.split("light")[1].split(".jpg")[0] }}'
    rele_2:
      name: relay_2
      select: "button[name=relayon2] ~ img"
      attribute: "src"
      value_template: '{{ value.split("light")[1].split(".jpg")[0] }}'

```
This option does not work now. And when I try to specify such a parameter in the new configuration option, I get a message that it does not exist. 

```
multiscrape:
  - resource: !secret pwr_sw_address
    username: !secret pwr_sw_username
    password: !secret pwr_sw_password
    scan_interval: 5
    sensor:
      - name: relay_1
        select: "button[name=relayon1] ~ img"
        attribute: "src"
        value_template: '{{ value.split("light")[1].split(".jpg")[0] }}'
      - name: relay_2
        select: "button[name=relayon2] ~ img"
        attribute: "src"
        value_template: '{{ value.split("light")[1].split(".jpg")[0] }}'

```
```

Logger: homeassistant.components.websocket_api.http.connection
Source: components/homeassistant/__init__.py:161
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:53:36 (1 occurrences)
Last logged: 11:53:36

[281471024226560] The system cannot restart because the configuration is not valid: Invalid config for [multiscrape]: [attribute] is an invalid option for [multiscrape]. Check: multiscrape->multiscrape->0->sensor->0->attribute. (See /home/homeassistant/.homeassistant/configuration.yaml, line 160).
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 728, in admin_handler
    await result
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/homeassistant/__init__.py", line 161, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Invalid config for [multiscrape]: [attribute] is an invalid option for [multiscrape]. Check: multiscrape->multiscrape->0->sensor->0->attribute. (See /home/homeassistant/.homeassistant/configuration.yaml, line 160). 

```

What do I need to do to get the value of the tag attributes?

**Comment by danieldotnl** [comment]
Thanks for filing this issue. Fixed it and published the fix in release v4.0.1.
