### ISSUE TITLE
Multiscrape broken in newest update?

### ISSUE THREAD

**Issue by WolfsWelpe** [danieldotnl/ha-multiscrape#31]
## Version of the custom_component

Installed component version: 4.0.1
Core Version: 2021.6.4
Supervisor: 2021.06.0
Host: Home Assistant OS 6.0

## Configuration

```yaml
- resource: http://192.168.178.45/livedata.htm
  scan_interval: 15
  sensor:
    - name: weatherstation_windspeed
      unit_of_measurement: km/h
      select: "input[name='avgwind'][type='text']"
      attribute: value
    - name: weatherstation_winddirection
      unit_of_measurement: °
      select: "input[name='windir'][type='text']"
      attribute: value
    - name: weatherstation_temperature
      unit_of_measurement: °C
      select: "input[name='outTemp'][type='text']"
      attribute: value
    - name: weatherstation_battery
      select: "input[name='outBattSta1'][type='text']"
      attribute: value
    - name: weatherstation_humidity
      unit_of_measurement: '%'
      select: "input[name='outHumi'][type='text']"
      attribute: value
    - name: weatherstation_uvi
      select: "input[name='uvi'][type='text']"
      attribute: value
    - name: weatherstation_solarradiation
      unit_of_measurement: w/m2
      select: "input[name='solarrad'][type='text']"
      attribute: value
    - name: weatherstation_eventrain
      unit_of_measurement: mm
      select: "input[name='eventr
```

## Describe the bug

Multiscrape is just not starting up anymore for me since the latest update. Before the update everything worked
fine with this configuration.

## Debug log

![Screenshot_1](https://user-images.githubusercontent.com/17033125/121775153-29aa1280-cb86-11eb-8f74-640dc264b806.png)

```text

Logger: custom_components.multiscrape
Source: custom_components/multiscrape/data.py:45
Integration: Multiscrape scraping component (documentation, issues)
First occurred: 13:52:46 (8 occurrences)
Last logged: 13:59:53

Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multiscrape/data.py", line 45, in async_update
    self.soup = BeautifulSoup(self.data, self._parser)
  File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
    elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()


```

**Comment by danieldotnl** [comment]
This indicates a connection problem with the site you are trying to scrape. Did you maybe forget the 'l' behind 'htm'?

**Comment by WolfsWelpe** [comment]
No the link is correct. And locally I can also reach the website without any problems.

**Comment by WolfsWelpe** [comment]
I also tried to establish a connection via SSH to the website, works fine.

![Screenshot_1](https://user-images.githubusercontent.com/17033125/121777359-ece41880-cb91-11eb-8120-22a4862f1976.png)

**Comment by WolfsWelpe** [comment]
Just downgraded to 2021.6.3 and its working again 👍

**Comment by danieldotnl** [comment]
I just upgraded myself and all is working fine for me. So can't reproduce at this moment :(

**Comment by WolfsWelpe** [comment]
Mhh that is unlucky :( 
I don't know which information I can give to reproduce :( Maybe it is the type of website? (Live Refresh im not sure tho)
Maybe a sample of the website could help? 

[LiveData.zip](https://github.com/danieldotnl/ha-multiscrape/files/6642737/LiveData.zip)

**Comment by kongo09** [comment]
This seems to be the same problem that I mentioned here: https://github.com/danieldotnl/ha-multiscrape/issues/27#issuecomment-861317831

For me, multiscrape stopped working as well. The target is reachable and available. My feeling is, the problem is not with multiscrape, but with the rest call, as I have other integrations complaining as well. Here are some log details:

Right after startup I see this:
```
2021-06-15 12:26:02 WARNING (MainThread) [homeassistant.components.sensor] Platform rest not ready yet: The request to ':///' is missing either an 'http://' or 'https://' protocol.; Retrying in background in 30 seconds
```

This is followed by these errors (logs from other integrations removed). You clearly see the two targets I try to scrape:
```
2021-06-15 12:26:05 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/status.asp failed with Server disconnected while attempting read
2021-06-15 12:26:05 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:26:05 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 1.025 seconds
2021-06-15 12:26:05 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/prtmaint/prtvolume.asp failed with Server disconnected while attempting read
2021-06-15 12:26:05 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:26:05 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 1.144 seconds
2021-06-15 12:26:05 WARNING (MainThread) [homeassistant.components.sensor] Platform multiscrape not ready yet: Server disconnected while attempting read; Retrying in background in 30 seconds
2021-06-15 12:26:05 WARNING (MainThread) [homeassistant.components.sensor] Platform multiscrape not ready yet: Server disconnected while attempting read; Retrying in background in 30 seconds
2021-06-15 12:26:05 WARNING (MainThread) [homeassistant.components.sensor] Platform multiscrape not ready yet: Server disconnected while attempting read; Retrying in background in 30 seconds
2021-06-15 12:26:05 WARNING (MainThread) [homeassistant.components.sensor] Platform multiscrape not ready yet: Server disconnected while attempting read; Retrying in background in 30 seconds
2021-06-15 12:26:06 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/status.asp failed with Server disconnected while attempting read
2021-06-15 12:26:06 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:26:06 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 0.750 seconds
2021-06-15 12:26:06 WARNING (MainThread) [homeassistant.components.sensor] Platform multiscrape not ready yet: Server disconnected while attempting read; Retrying in background in 30 seconds
2021-06-15 12:26:06 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/prtmaint/prtvolume.asp failed with Server disconnected while attempting read
2021-06-15 12:26:06 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:26:06 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 1.129 seconds
2021-06-15 12:26:06 WARNING (MainThread) [homeassistant.components.sensor] Platform multiscrape not ready yet: Server disconnected while attempting read; Retrying in background in 30 seconds
2021-06-15 12:26:13 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.staubsauger_karte is taking over 10 seconds
2021-06-15 12:26:46 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/status.asp failed with Server disconnected while attempting read
2021-06-15 12:26:46 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:26:46 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 0.593 seconds
2021-06-15 12:26:46 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/prtmaint/prtvolume.asp failed with Server disconnected while attempting read
2021-06-15 12:26:46 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:26:46 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 0.883 seconds
2021-06-15 12:27:46 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/status.asp failed with Server disconnected while attempting read
2021-06-15 12:27:46 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:27:46 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 0.754 seconds
2021-06-15 12:27:46 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/prtmaint/prtvolume.asp failed with Server disconnected while attempting read
2021-06-15 12:27:46 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:27:46 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 0.428 seconds
2021-06-15 12:29:16 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/status.asp failed with Server disconnected while attempting read
2021-06-15 12:29:16 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:29:16 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 0.722 seconds
2021-06-15 12:29:17 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/prtmaint/prtvolume.asp failed with Server disconnected while attempting read
2021-06-15 12:29:17 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:29:17 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 0.410 seconds
2021-06-15 12:29:27 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/status.asp failed with Server disconnected while attempting read
2021-06-15 12:29:27 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:29:27 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 0.756 seconds
2021-06-15 12:31:16 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/status.asp failed with Server disconnected while attempting read
2021-06-15 12:31:16 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:31:16 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 0.757 seconds
2021-06-15 12:31:17 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/prtmaint/prtvolume.asp failed with Server disconnected while attempting read
2021-06-15 12:31:17 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:31:17 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 0.424 seconds
2021-06-15 12:33:46 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/status.asp failed with Server disconnected while attempting read
2021-06-15 12:33:46 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:33:46 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 0.741 seconds
2021-06-15 12:33:48 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/prtmaint/prtvolume.asp failed with Server disconnected while attempting read
2021-06-15 12:33:48 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:33:48 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 0.430 seconds
2021-06-15 12:33:57 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/status.asp failed with Server disconnected while attempting read
2021-06-15 12:33:57 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 12:33:57 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 0.755 seconds
```

**Comment by kongo09** [comment]
Could it be related to this: https://github.com/home-assistant/core/pull/51799

**Comment by kongo09** [comment]
Weird enough, my error with the rest platform has disappeared after another restart of HA, but multiscrape still doesn't work:

```
2021-06-15 13:07:08 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/status.asp failed with Server disconnected while attempting read
2021-06-15 13:07:08 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 13:07:08 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 1.650 seconds
2021-06-15 13:07:08 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.0.20/prtmaint/prtvolume.asp failed with Server disconnected while attempting read
2021-06-15 13:07:08 ERROR (MainThread) [custom_components.multiscrape] Unexpected error fetching rest data data: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/multiscrape/data.py", line 45, in async_update
self.soup = BeautifulSoup(self.data, self._parser)
File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 310, in __init__
elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
2021-06-15 13:07:08 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 1.707 seconds
2021-06-15 13:07:08 WARNING (MainThread) [homeassistant.components.sensor] Platform multiscrape not ready yet: Server disconnected while attempting read; Retrying in background in 30 seconds
2021-06-15 13:07:08 WARNING (MainThread) [homeassistant.components.sensor] Platform multiscrape not ready yet: Server disconnected while attempting read; Retrying in background in 30 seconds
2021-06-15 13:07:08 WARNING (MainThread) [homeassistant.components.sensor] Platform multiscrape not ready yet: Server disconnected while attempting read; Retrying in background in 30 seconds
2021-06-15 13:07:08 WARNING (MainThread) [homeassistant.components.sensor] Platform multiscrape not ready yet: Server disconnected while attempting read; Retrying in background in 30 seconds
```

**Comment by danieldotnl** [comment]
I'm very curious whether 2021.6.5 did fix your issues?

**Comment by kongo09** [comment]
> 2021.6.5

I cannot see it in my supervisor yet. Will upgrade and try as soon as it arrives.

**Comment by WolfsWelpe** [comment]
Heyho just installed 2021.6.5 ^^
It's working again :)

**Comment by WolfsWelpe** [comment]
Heyho just installed 2021.6.5 ^^
It's working again :)

**Comment by kongo09** [comment]
Yes, I can also confirm this solves the problem for me as well.
