### ISSUE TITLE
with "unit of measurement" the code fails to return any data

### ISSUE THREAD

**Issue by kvacha13** [danieldotnl/ha-multiscrape#329]
Multiscrape 6.8.1
HA Core
2024.2.3
Supervisor
2024.02.0
Operating System
11.5
Frontend
20240207.1

- resource: https://www.eneco.nl/duurzame-energie/modelcontract/
  scan_interval: 28800
  sensor:
    - unique_id: electricity_price_normal
      name: Electricity price normal
      select: "tbody > tr > td:nth-child(2)"
      unit_of_measurement: "°C"
      value_template: '{{value.split("€")[1]}}'

Describe the bug
adding "unit_of_measurement" to the code fails to return any data, but without it (UOM) it returns. 
Then I removed UOM and added another property "state_class: measurement" and with it the code also failed to return data.
 The scrapper returns data only with this code:

- resource: https://www.eneco.nl/duurzame-energie/modelcontract/
  scan_interval: 28800
  sensor:
    - unique_id: electricity_price_normal
      name: Electricity price normal
      select: "tbody > tr > td:nth-child(2)"
     #unit_of_measurement: "°C"
     #state_class: measurement
      value_template: '{{value.split("€")[1]}}'

**Comment by danieldotnl** [comment]
Please, post your debug logging.

**Comment by kvacha13** [comment]
Hi Daniel. Thank you for replying. Here is error logs:
Log Details (ERROR)
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:352
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 10:14:37 (1 occurrences)
Last logged: 10:14:37

Error while setting up multiscrape platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 669, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'TupleWrapper'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 782, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1325, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1047, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 995, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 671, in state
    raise ValueError(
ValueError: Sensor sensor.electricity_price_normal has device class 'None', state class 'None' unit 'F' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '0,37668' (<class 'homeassistant.helpers.template.TupleWrapper'>)

**Comment by danieldotnl** [comment]
It looks like HA doesn't recognize the state as a number. Try replacing the comma with a dot in a value template.

**Comment by kvacha13** [comment]
Thank you Daniel. That was it. replaced comma with dot and it worked👍
