### ISSUE TITLE
Problems after upgrade from old version, No module named 'bs4' 

### ISSUE THREAD

**Issue by raderarn** [danieldotnl/ha-multiscrape#39]
## Version of the custom_component
5.1.1

## Configuration
```yaml
multiscrape:
  - name: home assistant scraper
    resource: https://www.home-assistant.io
    scan_interval: 3600
    sensor:
      - unique_id: version
        name: Latest version
        select: ".current-version > h1:nth-child(1)"
        value_template: '{{ (value.split(":")[1]) }}'
```

## Describe the bug

After upgrade from the old version, I'm having a problem with dependencies. I get an error that bs4 is missing. I am running python 3.9 and Debian Bullseye.
If I install beautifulsoap4 then I get a new error saying "AttributeError: 'ScrapedRestData' object has no attribute 'soup'"
I am trying with your example code just to make sure it's not my configuration.
Do you have any idea what I should do?

## Debug log

```text
2021-07-25 18:49:30 ERROR (MainThread) [homeassistant.config] Package temperaturarena setup failed. Integration multiscrape No module named 'bs4' (See /root/.homeassistant/packages/temperaturarena.yaml:0).
```

```text
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity.py", line 665, in add_to_platform_finish
await self.async_added_to_hass()
File "/usr/local/lib/python3.9/dist-packages/homeassistant/components/rest/entity.py", line 64, in async_added_to_hass
self._update_from_rest_data()
File "/root/.homeassistant/custom_components/multiscrape/sensor.py", line 155, in _update_from_rest_data
self.rest.soup,
AttributeError: 'ScrapedRestData' object has no attribute 'soup'
```

**Comment by danieldotnl** [comment]
Strange problem... home assistant should automagically install beautifulsoup when multiscrape is loaded.

Is this all you have in the logging? I would expect errors earlier in the process.

**Comment by raderarn** [comment]
When I don't have beautifulsoup4 installed, there are no more logs. But when it's installed, there are more logs, yes:

```
2021-07-29 09:49:46 ERROR (MainThread) [custom_components.multiscrape.data] Unable to parse response.
2021-07-29 09:49:47 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform multiscrape
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity.py", line 665, in add_to_platform_finish
await self.async_added_to_hass()
File "/usr/local/lib/python3.9/dist-packages/homeassistant/components/rest/entity.py", line 64, in async_added_to_hass
self._update_from_rest_data()
File "/root/.homeassistant/custom_components/multiscrape/sensor.py", line 155, in _update_from_rest_data
self.rest.soup,
AttributeError: 'ScrapedRestData' object has no attribute 'soup'
2021-07-29 09:49:47 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up multiscrape platform for sensor
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity.py", line 665, in add_to_platform_finish
await self.async_added_to_hass()
File "/usr/local/lib/python3.9/dist-packages/homeassistant/components/rest/entity.py", line 64, in async_added_to_hass
self._update_from_rest_data()
File "/root/.homeassistant/custom_components/multiscrape/sensor.py", line 155, in _update_from_rest_data
self.rest.soup,
AttributeError: 'ScrapedRestData' object has no attribute 'soup'
```

As I mentioned, it might be my installation that is the problem. I have no virtual environment and use root as user. There is a history behind this choice :)

**Comment by danieldotnl** [comment]
Could you enable DEBUG logging?

**Comment by raderarn** [comment]
Ok, here is a more detailed log. tree builder?

```2021-07-31 18:13:01 DEBUG (MainThread) [custom_components.multiscrape.data] Updating from https://www.home-assistant.io
2021-07-31 18:13:02 ERROR (MainThread) [custom_components.multiscrape.data] Unable to parse response.
2021-07-31 18:13:02 DEBUG (MainThread) [custom_components.multiscrape.data] Exception parsing resonse: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2021-07-31 18:13:02 DEBUG (MainThread) [custom_components.multiscrape] Finished fetching rest data data in 1.253 seconds
2021-07-31 18:13:03 DEBUG (MainThread) [custom_components.multiscrape.sensor] Rendered select template: .current-version > h1:nth-child(1)
2021-07-31 18:13:03 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform multiscrape
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity.py", line 665, in add_to_platform_finish
await self.async_added_to_hass()
File "/usr/local/lib/python3.9/dist-packages/homeassistant/components/rest/entity.py", line 64, in async_added_to_hass
self._update_from_rest_data()
File "/root/.homeassistant/custom_components/multiscrape/sensor.py", line 155, in _update_from_rest_data
self.rest.soup,
AttributeError: 'ScrapedRestData' object has no attribute 'soup'
2021-07-31 18:13:03 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up multiscrape platform for sensor
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/entity.py", line 665, in add_to_platform_finish
await self.async_added_to_hass()
File "/usr/local/lib/python3.9/dist-packages/homeassistant/components/rest/entity.py", line 64, in async_added_to_hass
self._update_from_rest_data()
File "/root/.homeassistant/custom_components/multiscrape/sensor.py", line 155, in _update_from_rest_data
self.rest.soup,
AttributeError: 'ScrapedRestData' object has no attribute 'soup'```

**Comment by raderarn** [comment]
I found this:

https://stackoverflow.com/questions/24398302/bs4-featurenotfound-couldnt-find-a-tree-builder-with-the-features-you-requeste

And installed:

pip install bs4
pip install html5lib
pip install lxml

Now it's working :)

**Comment by danieldotnl** [comment]
That's great! If you encounter this again (with another component), check the dependencies in the manifest file.
Enjoy using multiscrape!
