### ISSUE TITLE
Fetched value  write to HA sensor overflow

### ISSUE THREAD

**Issue by espe20** [danieldotnl/ha-multiscrape#454]
## Version of the custom_component

8.0.2

## Configuration

```yaml
multiscrape:
  - name: HA multiscraper
    resource: https://www.kalbi.pl/
    scan_interval: 3600
    sensor:
      - unique_id: kalbi-dayEvent
        name: kalbi-dayEvent
        select: ".calCard-ententa"
        value_template: "{{ value | trim }}"
```

## Describe the bug

Fetching data longer that defined HA sensor max length throws an error in HA instead in multiscrape component.
component should trim value before set value to sensor:
![image](https://github.com/user-attachments/assets/8f9a55e5-a820-42df-8105-7452e6784fd7)

## Debug log

```text

2024-11-21 09:37:21.064 DEBUG (MainThread) [custom_components.multiscrape.http] HA multiscraper # Response status code received: 200
2024-11-21 09:37:21.064 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA multiscraper # Loading the content in BeautifulSoup.
2024-11-21 09:37:21.185 DEBUG (MainThread) [custom_components.multiscrape.coordinator] HA multiscraper # Data successfully refreshed. Sensors will now start scraping to update.
2024-11-21 09:37:21.185 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Finished fetching multiscrape data in 0.330 seconds (success: True)
2024-11-21 09:37:21.185 DEBUG (MainThread) [custom_components.multiscrape.sensor] HA multiscraper # kalbi-dayEvent # Start scraping to update sensor
2024-11-21 09:37:21.186 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA multiscraper # kalbi-dayEvent # Tag selected: <section class="calCard-ententa">
<h3 class="calCard-ententa-t">Nietypowe święta:</h3>
<a href="https://www.kalbi.pl/swiatowy-dzien-filozofii" title="Światowy Dzień Filozofii"> Światowy Dzień Filozofii</a> <br/><a href="https://www.kalbi.pl/swieto-mlodego-wina" title="Święto Młodego Wina"> Święto Młodego Wina</a> <br/><a href="https://www.kalbi.pl/swiatowy-dzien-rzucania-palenia-tytoniu" title="Światowy Dzień Rzucania Palenia Tytoniu"> Światowy Dzień Rzucania Palenia Tytoniu</a> <br/><a href="https://www.kalbi.pl/swiatowy-dzien-rybolowstwa" title="Światowy Dzień Rybołówstwa"> Światowy Dzień Rybołówstwa</a> <br/><a href="https://www.kalbi.pl/dzien-pracownika-socjalnego" title="Dzień Pracownika Socjalnego"> Dzień Pracownika Socjalnego</a> <br/><a href="https://www.kalbi.pl/swiatowy-dzien-zyczliwosci-i-pozdrowien" title="Światowy Dzień Życzliwości i Pozdrowień"> Światowy Dzień Życzliwości i Pozdrowień</a> <br/><a href="https://www.kalbi.pl/swiatowy-dzien-telewizji" title="Światowy Dzień Telewizji"> Światowy Dzień Telewizji</a> <br/><a href="https://www.kalbi.pl/swieto-sluzby-czolgowo-samochodowej" title="Święto Służby Czołgowo-Samochodowej"> Święto Służby Czołgowo-Samochodowej</a> <br/> </section>
2024-11-21 09:37:21.187 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA multiscraper # kalbi-dayEvent # Selector result: 
Nietypowe święta:
 Światowy Dzień Filozofii  Święto Młodego Wina  Światowy Dzień Rzucania Palenia Tytoniu  Światowy Dzień Rybołówstwa  Dzień Pracownika Socjalnego  Światowy Dzień Życzliwości i Pozdrowień  Światowy Dzień Telewizji  Święto Służby Czołgowo-Samochodowej  
2024-11-21 09:37:21.187 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA multiscraper # kalbi-dayEvent # Applying value_template on selector result
2024-11-21 09:37:21.187 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA multiscraper # kalbi-dayEvent # Final selector value: Nietypowe święta:
 Światowy Dzień Filozofii  Święto Młodego Wina  Światowy Dzień Rzucania Palenia Tytoniu  Światowy Dzień Rybołówstwa  Dzień Pracownika Socjalnego  Światowy Dzień Życzliwości i Pozdrowień  Światowy Dzień Telewizji  Święto Służby Czołgowo-Samochodowej of type <class 'str'>
2024-11-21 09:37:21.187 DEBUG (MainThread) [custom_components.multiscrape.sensor] HA multiscraper # kalbi-dayEvent # Selected: Nietypowe święta:
 Światowy Dzień Filozofii  Święto Młodego Wina  Światowy Dzień Rzucania Palenia Tytoniu  Światowy Dzień Rybołówstwa  Dzień Pracownika Socjalnego  Światowy Dzień Życzliwości i Pozdrowień  Światowy Dzień Telewizji  Święto Służby Czołgowo-Samochodowej
2024-11-21 09:37:21.187 ERROR (MainThread) [homeassistant.helpers.entity] Failed to set state for sensor.kalbi_dayevent, fall back to unknown
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1211, in _async_write_ha_state
    hass.states.async_set_internal(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2373, in async_set_internal
    state = State(
            ^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1817, in __init__
    validate_state(state)
  File "/usr/src/homeassistant/homeassistant/core.py", line 246, in validate_state
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state with length 266. State max length is 255 characters.
2024-11-21 09:37:21.202 DEBUG (MainThread) [custom_components.multiscrape.entity] HA multiscraper # kalbi-dayEvent # Sensor updated and state written to HA

```

**Comment by danieldotnl** [comment]
I disagree that this should be the default behavior in multiscrape. I think HA core should decide what to do when the content is too long (and also how long the max is). Other components in core like the rest sensor also don't handle it.
You could of course truncate the value with a value_template.
